name: Python application test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flask flask_testing pymongo requests mock pytest-mock
      - name: Run Tests
        env:
          MONGO_URI: mongodb://localhost:27017/test_db
          FLASK_SECRET_KEY: fake_secret_key
          OPENAI_API_KEY: fake_secret_key
        run: |
          cd backend
          pytest
